<div class="div-box">
    <div class="title">
        <?= car_t($t, 'Quick Access'); ?>
    </div>
    <div class="line">
        <a href="<?= CAR_PATH_WEB; ?>/dash/deck-list"><?= car_t($t, 'Decks'); ?></a>
    </div>
    <div class="line">
        <a href="<?= CAR_PATH_WEB; ?>/dash/deck-new-act"><?= car_t($t, 'New Deck'); ?></a>
    </div>
    <div class="line">
        <a href="<?= CAR_PATH_WEB . '/profile/srs'; ?>"><?= car_t($t, 'Spaced Repetition System (SRS)'); ?></a>
    </div>
    <div class="line">
        <a href="<?= CAR_PATH_WEB . '/profile/profile'; ?>"><?= car_t($t, 'Profile'); ?></a>
    </div>
</div>
