<div class="div-box">
    <div class="title">
        <?= cal_t($t, 'Quick Access'); ?>
    </div>
    <div class="line">
        <a href="<?= CAL_PATH_WEB; ?>/dash/deck-list"><?= cal_t($t, 'Decks'); ?></a>
    </div>
    <div class="line">
        <a href="<?= CAL_PATH_WEB; ?>/dash/deck-new-act"><?= cal_t($t, 'New Deck'); ?></a>
    </div>
    <div class="line">
        <a href="<?= CAL_PATH_WEB . '/profile/srs'; ?>"><?= cal_t($t, 'Spaced Repetition System (SRS)'); ?></a>
    </div>
    <div class="line">
        <a href="<?= CAL_PATH_WEB . '/profile/profile'; ?>"><?= cal_t($t, 'Profile'); ?></a>
    </div>
</div>
